# Generated by Django 4.registry.7 on 2023-03-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название больницы')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Объект закупки')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена')),
                ('arrive_data', models.DateField(verbose_name='Дата поступления')),
                ('sent_fin_data', models.DateField(verbose_name='Дата отправки в ФУ')),
                ('sent_hospital_data', models.DateField(verbose_name='Дата отправки в больницу')),
                ('sent_correct_data', models.DateField(verbose_name='Дата отправки на доработку')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('p9', models.BooleanField(verbose_name='Закупка по п.9')),
                ('repair', models.BooleanField(verbose_name='Ремонт')),
                ('develop_DED', models.BooleanField(verbose_name='ПСД')),
                ('hospital_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.hospital', verbose_name='Название больницы')),
            ],
        ),
    ]
