# Generated by Django 4.registry.7 on 2023-03-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='PDF_scan',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='comment_text',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sent_correct_data',
            field=models.DateField(blank=True, verbose_name='Дата отправки на доработку'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sent_fin_data',
            field=models.DateField(blank=True, verbose_name='Дата отправки в ФУ'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='sent_hospital_data',
            field=models.DateField(blank=True, verbose_name='Дата отправки в больницу'),
        ),
    ]
