# Generated by Django 4.1.7 on 2023-04-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_alter_purchase_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='PDF_scan',
            field=models.FileField(blank=True, null=True, upload_to='PDF/'),
        ),
    ]
